site_name: Cue Docs
site_description: Documentation for Cue - Distributed in-memory job queue with Raft
site_url: https://m-javani.github.io/cue-docs/
repo_url: https://github.com/m-javani/cue
repo_name: m-javani/cue
edit_uri: edit/main/docs/

theme:
  name: material
  logo: assets/logos/logo-white.png
  favicon: favicon.png
  palette:
    - scheme: default
      primary: indigo
      accent: cyan
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    - scheme: slate
      primary: indigo
      accent: cyan
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  features:
    - navigation.tabs
    - navigation.sections
    - navigation.expand
    - navigation.indexes
    - navigation.top
    - content.code.copy
    - content.tabs.link
    - search.suggest
    - search.highlight
  

nav:
  - Home: index.md
  - Cue:
    - Overview: cue/overview.md
    - Installation: cue/installation.md
    - Quick Start: cue/quickstart.md
    - Configuration: cue/configuration.md
    - Cluster Management: cue/cluster-management.md
    - Monitoring: cue/monitoring.md
    - Deployment: cue/deployment.md
    - Limitations: cue/limitations.md
  - CueProxy:
    - Overview: cueproxy/overview.md
    - Installation: cueproxy/installation.md
    - Quick Start: cueproxy/quickstart.md
    - API Reference: cueproxy/api.md
    - Configuration: cueproxy/configuration.md
    - Authentication: cueproxy/authentication.md
    - Deployment: cueproxy/deployment.md
    - Monitoring: cueproxy/monitoring.md
  - Contributing: contributing.md

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - admonition
  - pymdownx.details
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - toc:
      permalink: true

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/m-javani/cue
      
extra_css:
  - stylesheets/extra.css